// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 2EhpMjay9KyV5XM6pPwG1U
// Component: rtEt3XoWqNa
import * as React from "react";
import Head from "next/head";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import Button from "../../Button"; // plasmic-import: LtqRT1LJmaR/component
import "@plasmicapp/react-web/lib/plasmic.css";
import * as projectcss from "./plasmic_infosite_nuxt.module.css"; // plasmic-import: 2EhpMjay9KyV5XM6pPwG1U/projectcss
import * as sty from "./PlasmicHomepage.module.css"; // plasmic-import: rtEt3XoWqNa/css
import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: MIiSgAk7pge/icon
import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: CO3xSz3XrNUg/icon

export const PlasmicHomepage__VariantProps = new Array();

export const PlasmicHomepage__ArgProps = new Array();

function PlasmicHomepage__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <p.Stack
          as={"div"}
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          hasGap={true}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            className={classNames(projectcss.all, sty.header)}
          >
            <h1
              data-plasmic-name={"h1"}
              data-plasmic-override={overrides.h1}
              className={classNames(
                projectcss.h1,
                projectcss.__wab_text,
                sty.h1
              )}
            >
              {"NepEcht!"}
            </h1>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__tcTyM
              )}
            >
              {
                "Het project NepEcht! richt zich op het helpen van jongvolwassenen met psychische beperking en een licht verstandelijke beperking (LVB) om makkelijker de echtheid van online informatie te kunnen duiden. Er wordt een applicatie ontwikkeld die hen daarbij ondersteunt. Om een bruikbare applicatie te ontwikkelen die aansluit bij de behoeften en interesses van de doelgroep, wordt in dit project nauw samengewerkt met de jongvolwassenen die baat hebben bij deze applicatie en hun begeleiders."
              }
            </div>

            <Button
              data-plasmic-name={"button"}
              data-plasmic-override={overrides.button}
              className={classNames("__wab_instance", sty.button)}
              endIcon={
                <Icon3Icon
                  className={classNames(projectcss.all, sty.svg__iWi9V)}
                  role={"img"}
                />
              }
              link={"https://nepecht-dev.netlify.app"}
              showEndIcon={"showEndIcon"}
              startIcon={
                <IconIcon
                  className={classNames(projectcss.all, sty.svg__mk4Rv)}
                  role={"img"}
                />
              }
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__hwxn2
                )}
              >
                {"Ga naar de app"}
              </div>
            </Button>
          </div>

          <div
            data-plasmic-name={"nepEchtApp"}
            data-plasmic-override={overrides.nepEchtApp}
            className={classNames(projectcss.all, sty.nepEchtApp)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__g9Lv
              )}
            >
              {"De NepEcht! app"}
            </div>

            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img___766M5)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"70%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"100%"}
              loading={"lazy"}
              src={{
                src: "/plasmic/infosite_nuxt/images/threephonespng.png",
                fullWidth: 1920,
                fullHeight: 1081,
                aspectRatio: undefined
              }}
            />

            <div
              data-plasmic-name={"columns"}
              data-plasmic-override={overrides.columns}
              className={classNames(projectcss.all, sty.columns)}
            >
              <div className={classNames(projectcss.all, sty.column__bPcmm)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__iSa1Z
                  )}
                >
                  {"Bekende platformen"}
                </div>
              </div>

              <div className={classNames(projectcss.all, sty.column__yuRgo)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__v7GoA
                  )}
                >
                  {"Adviezen met tips"}
                </div>
              </div>

              <div className={classNames(projectcss.all, sty.column__j43SI)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__kuQwu
                  )}
                >
                  {"Makkelijk in gebruik"}
                </div>
              </div>
            </div>
          </div>

          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__r5Hsp
            )}
          >
            {"Wat kan er gecontroleerd worden?"}
          </div>

          <div
            data-plasmic-name={"topics"}
            data-plasmic-override={overrides.topics}
            className={classNames(projectcss.all, sty.topics)}
          >
            <div
              data-plasmic-name={"nieuwsEnEvenementen"}
              data-plasmic-override={overrides.nieuwsEnEvenementen}
              className={classNames(projectcss.all, sty.nieuwsEnEvenementen)}
            >
              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__rWTb4)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100px"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/infosite_nuxt/images/image9.svg",
                  fullWidth: 150,
                  fullHeight: 150,
                  aspectRatio: 1
                }}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__k3NMv
                )}
              >
                {"Nieuws en evenementen"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__tTxu2
                )}
              >
                {"Video's\nEvenementen\nReacties op berichten\nArtikelen"}
              </div>
            </div>

            <div
              data-plasmic-name={"contactEnAfzender"}
              data-plasmic-override={overrides.contactEnAfzender}
              className={classNames(projectcss.all, sty.contactEnAfzender)}
            >
              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__fakff)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100px"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/infosite_nuxt/images/image8.svg",
                  fullWidth: 150,
                  fullHeight: 150,
                  aspectRatio: 1
                }}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__vhafO
                )}
              >
                {"Contact en afzender"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__igW80
                )}
              >
                {
                  "Profielen\nBerichten\nGebeld worden\nToegevoegd aan een groep\nOmegle"
                }
              </div>
            </div>

            <div
              data-plasmic-name={"reclame"}
              data-plasmic-override={overrides.reclame}
              className={classNames(projectcss.all, sty.reclame)}
            >
              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__oNu8)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100px"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/infosite_nuxt/images/image7.svg",
                  fullWidth: 150,
                  fullHeight: 150,
                  aspectRatio: 1
                }}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__e17Bu
                )}
              >
                {"Reclame, kopen en verkopen"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___8OLQa
                )}
              >
                {"Reclame\nIets verkopen\nIets kopen"}
              </div>
            </div>
          </div>

          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__n2Wu2
            )}
          >
            {"Samenwerkingen"}
          </div>

          <div
            data-plasmic-name={"samenwerking"}
            data-plasmic-override={overrides.samenwerking}
            className={classNames(projectcss.all, sty.samenwerking)}
          >
            <div
              data-plasmic-name={"fno"}
              data-plasmic-override={overrides.fno}
              className={classNames(projectcss.all, sty.fno)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__snIqs)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img___3L3Xu)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/infosite_nuxt/images/image.jpeg",
                    fullWidth: 513,
                    fullHeight: 420,
                    aspectRatio: undefined
                  }}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__qW1Tx
                  )}
                >
                  {"FNO Geestkracht"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__oncVo
                  )}
                >
                  {
                    "Het project NepEcht! is mogelijk gemaakt door FNO. Het programma GeestKracht van FNO wil dat elke jongvolwassene (16-35 jaar) zichzelf kan zijn en ook met een psychische kwetsbaarheid krachtig kan (blijven) meedoen in de maatschappij. GeestKracht richt zich op preventie van het ontstaan van psychische problemen, op het beperken van de praktische gevolgen ervan en op het bevorderen van maatschappelijke participatie."
                  }
                </div>
              </div>
            </div>

            <div
              data-plasmic-name={"frionVitree"}
              data-plasmic-override={overrides.frionVitree}
              className={classNames(projectcss.all, sty.frionVitree)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__sJ6Y1)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__bkY3)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/infosite_nuxt/images/image4.png",
                    fullWidth: 1074,
                    fullHeight: 463,
                    aspectRatio: undefined
                  }}
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__s4Rym)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/infosite_nuxt/images/image2.jpeg",
                    fullWidth: 2480,
                    fullHeight: 1024,
                    aspectRatio: undefined
                  }}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__pnJtv
                  )}
                >
                  {"Frion & Vitree"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__krQFu
                  )}
                >
                  {
                    "Tijdens dit project wordt er samengewerkt met jeugdhulporganisaties Frion en Vitree. Deze organisaties zullen helpen met het ontwikkelen van de applicatie. Dit wordt gedaan door de jongvolwassenen van deze organisaties nauw te betrekken bij het project."
                  }
                </div>
              </div>
            </div>

            <div
              data-plasmic-name={"windesheim"}
              data-plasmic-override={overrides.windesheim}
              className={classNames(projectcss.all, sty.windesheim)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__wfBob)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__vqLeQ)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/infosite_nuxt/images/image3.svg",
                    fullWidth: 300,
                    fullHeight: 146,
                    aspectRatio: 2.051932
                  }}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__clzoX
                  )}
                >
                  {"Hogeschool Windesheim"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__erJmw
                  )}
                >
                  {
                    "Dit project wordt geleid door het Lectoraat Jeugd & Media van het Windesheim. Studenten van de Social Works minor Child & Media gaan samen met studenten van de ICT minor Mobile Solutions werken aan de app."
                  }
                </div>
              </div>
            </div>
          </div>

          <div
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames(projectcss.all, sty.footer)}
          >
            <div
              data-plasmic-name={"copyright"}
              data-plasmic-override={overrides.copyright}
              className={classNames(projectcss.all, sty.copyright)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__dx39
                )}
              >
                {"© 2021 NepEcht! all rights reserved"}
              </div>
            </div>
          </div>
        </p.Stack>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "header",
    "h1",
    "button",
    "nepEchtApp",
    "columns",
    "topics",
    "nieuwsEnEvenementen",
    "contactEnAfzender",
    "reclame",
    "samenwerking",
    "fno",
    "frionVitree",
    "windesheim",
    "footer",
    "copyright"
  ],

  header: ["header", "h1", "button"],
  h1: ["h1"],
  button: ["button"],
  nepEchtApp: ["nepEchtApp", "columns"],
  columns: ["columns"],
  topics: ["topics", "nieuwsEnEvenementen", "contactEnAfzender", "reclame"],
  nieuwsEnEvenementen: ["nieuwsEnEvenementen"],
  contactEnAfzender: ["contactEnAfzender"],
  reclame: ["reclame"],
  samenwerking: ["samenwerking", "fno", "frionVitree", "windesheim"],
  fno: ["fno"],
  frionVitree: ["frionVitree"],
  windesheim: ["windesheim"],
  footer: ["footer", "copyright"],
  copyright: ["copyright"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHomepage__ArgProps,
      internalVariantPropNames: PlasmicHomepage__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    h1: makeNodeComponent("h1"),
    button: makeNodeComponent("button"),
    nepEchtApp: makeNodeComponent("nepEchtApp"),
    columns: makeNodeComponent("columns"),
    topics: makeNodeComponent("topics"),
    nieuwsEnEvenementen: makeNodeComponent("nieuwsEnEvenementen"),
    contactEnAfzender: makeNodeComponent("contactEnAfzender"),
    reclame: makeNodeComponent("reclame"),
    samenwerking: makeNodeComponent("samenwerking"),
    fno: makeNodeComponent("fno"),
    frionVitree: makeNodeComponent("frionVitree"),
    windesheim: makeNodeComponent("windesheim"),
    footer: makeNodeComponent("footer"),
    copyright: makeNodeComponent("copyright"),
    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
